<div class="footer">
                <div class="footer__main">
                    <div class="container footer__main-flex">
                        <div class="footer__main-column">
                            <div class="footer__main-column__header">
                                Главное
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Документы</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">О Компании</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Покрытия</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Сервис</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Новости и акции</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Цены</a>
                            </div>
                        </div>
                        <div class="footer__main-column">
                            <div class="footer__main-column__header">
                                Каталог
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Документы</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">О Компании</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Покрытия</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Сервис</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Новости и акции</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Цены</a>
                            </div>
                        </div>
                        <div class="footer__main-column">
                            <div class="footer__main-column__header">
                                Дополнительно
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Документы</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">О Компании</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Покрытия</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Сервис</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Новости и акции</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="#">Цены</a>
                            </div>
                        </div>
                        <div class="footer__main-column footer__contacts">
                            <div class="footer__main-column__header">
                                <a href="tel:+78007700041">8 (800) 770-00-41</a>
                            </div>
                            <div class="footer__main-column__elem">
                                <a href="mailto:">akp-market@bk.ru</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer__copyright-panel">
                    <div class="container footer__copyright-panel__flex">
                        <div class="footer__copyright-panel__logo">
                            <img src="img/logo_silver.png" alt="">
                            <span>Все права защищены © 2006—2021</span>
                        </div>
                        <div class="footer__copyright-panel__text">
                        <div>Сайт www.grandline.ru носит исключительно информационный характер и ни при каких условиях не является публичной офертой, определяемой положениями ГК РФ. Для получения подробной информации о наличии, видах, характеристиках и стоимости материалов, пожалуйста, обращайтесь в офисы продаж.</div> <br>

                        <span>Внимание! Цвет продукции может отличаться от изображения на сайте ввиду особенностей цветопередачи монитора и восприятия.</span>
                        </div>
                        <div class="footer__copyright-panel__message">
                            <a href="">Отправить сообщение</a>
                        </div>
                    </div>
                </div>
                <div class="footer__developer-info">
                    
                </div>
        </div>