<div class="header">
            <div class="header__main">
                <div class="container">
                    <div class="header__main-inner">
                        <div class="header__logo">
                            <a href="in-fas.ru"><img id="logo" src="img/logo.png" alt=""></a>
                            <div class="header__logo-text">
                                    <div class="header__logo-text-elem">
                                        Завод
                                    </div>
                                    <div class="header__logo-text-elem">
                                        Фасадных
                                    </div>
                                    <div class="header__logo-text-elem">
                                        Конструкций
                                    </div>
                            </div>
                            <div class="header__city">
                                <a href="#" data-modal="choose-city-modal" class="header__active-city hide-on-m">
                                    <img class="down-arrow" src="img/down-arrow.png" alt="">
                                    <span class="header__active-city__underline" id="header_city_name_text">Екатеринбург</span>
                                </a>
                            </div>
                        </div>
                        <ul class="header__menu">
                            <li class="header__menu-item">
                                <a class="header__menu-link" href="/delivery.html">Доставка</a>
                            </li>
                            <li class="header__menu-item">
                                <a class="header__menu-link" href="/delivery.html">Оплата</a>
                            </li>
                            <li class="header__menu-item">
                                <a class="header__menu-link" href="/delivery.html">Гарантия</a>
                            </li>
                            <li class="header__menu-item">
                                <a class="header__menu-link" href="/delivery.html">Поддержка</a>
                            </li>
                            <li class="header__menu-item">
                                <a class="header__menu-link" href="/delivery.html">Контакты</a>
                            </li>
                        </ul>
                        <div class="header__mail-logo">
                            <img src="img/email.png" alt="">
                        </div>
                        <div class="header__mail">
                            <div class="header__mail-href">
                                <a href="mailto:">akp-market@bk.ru</a>
                            </div>
                            <div class="header__mail-text">
                                <a href="mailto:">Наша почта</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header__sub-panel">
                <div class="container btn_container">
                    <div class="btn_container__left">
                        <div class="btn-panel">
                            <img class="burger-line" src="img/reorder-option.png" alt="">
                            <button id="btn-catalog" class="btn btn-default"><span id="catalog_text">Каталог товаров</span></button>
                        </div>
                        <div class="btn-panel btn-panel-margin">
                            <img class="arrow-down-white" src="img/arrow-down-sign-to-navigate.png" alt="">
                            <button id="btn-services" class="btn btn-sub"><span id="calculation_text">Сервисы расчета</span></button>
                        </div>
                    </div>
                    <div class="btn_container__right">
                        <div class="callback__whatsapp-logo">
                            <img src="img/whatsapp.png" alt="">
                        </div>
                        <div class="callback">
                                <div class="callback__number callback__number-whatsapp">
                                    <a href="tel:+78007700041">8 (800) 770-00-41</a>
                                </div>
                                <div class="callback__feedback">
                                    <a href="#">Написать нам в чате</a>
                                </div>
                        </div>
                        <div class="callback__phone-logo">
                            <img src="img/phone-call.png" alt="">
                        </div>
                        <div class="callback">
                                <div class="callback__number">
                                    <a href="tel:+78007700041">8 (800) 770-00-41</a>
                                </div>
                                <div class="callback__feedback">
                                    <a href="#">Заказать обратный звонок</a>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="catalog open-catalog">
            <div class="container catalog__margin">
                <div class="catalog__menu">
                    <div class="catalog__menu-list">
                        <ul id="list">
                            <div class="list__hover">
                                <li id="catalog-elem-active"><a href="#">Композитный фасад</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed list__detailed-active">
                                        <div class="list__detailed-title">
                                            Композитный фасад
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="list__hover">
                                <li><a href="#">Штукатурный фасад</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed">
                                        <div class="list__detailed-title">
                                            Штукатурный фасад
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="list__hover">
                                <li><a href="#">Фасад из керамогранита</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed">
                                        <div class="list__detailed-title">
                                            Фасад из керамогранита
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="list__hover">
                                <li><a href="#">Утеплитель</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed">
                                        <div class="list__detailed-title">
                                            Утеплитель
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="list__hover">
                                <li><a href="#">Крепление для фасада</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed">
                                        <div class="list__detailed-title">
                                            Крепление для фасад
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="list__hover">
                                <li><a href="#">Услуги</a><img src="img/right-arrow.png" alt=""></li>
                                <div class="list__detailed">
                                        <div class="list__detailed-title">
                                            Услуги
                                        </div>
                                    <br>
                                    <div class="list__detailed-block">
                                        <div class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                        <div style="margin-top: 25px" class="list__detailed-row">
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                            <div class="list__detailed-text">
                                                <a class="text__title" href="#">Толщина</a>
                                                <br>
                                                <a class="text__sub" href="#">3 мм</a>
                                                <br>
                                                <a class="text__sub" href="#">4 мм</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="catalog__shadow-bg"></div>
        </div>

        <div class="services-calc container open-services-calc">
            <div class="services-calc__container">
                <ul>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Подбор цвета и материалов</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                    <li><img src="img/home.png" alt=""><a href="#" class="services-calc__elem">Калькулятор фасада</a></li>
                </ul>
            </div>
        </div>